name: budget
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^10.3.0+2
  form_builder_validators: ^11.3.0
  form_builder_extra_fields: ^12.2.0
  http: ^1.2.0
  flutter_secure_storage: ^10.0.0
  json_annotation: ^4.8.1
  intl: any
  json_serializable: ^6.7.1
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  webview_flutter: ^4.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - .env
    - .env.dev
